In [45]:
import numpy as np
import pandas as pd

In [46]:
s = pd.Series([1,3,5, np.nan, 6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [47]:
dates = pd.date_range("20130101", periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')

In [48]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01  0.150654  1.901648 -0.890335  1.205825
2013-01-02  1.780011 -1.229151 -0.118814  2.458067
2013-01-03  0.086420 -0.740265 -1.428083  0.093868
2013-01-04  0.971432  0.721757 -1.443037  0.103568
2013-01-05  0.102880  0.802461  0.213550 -1.079248
2013-01-06  0.411632  0.176465 -0.116215 -1.248752

In [49]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [50]:
df2.dtypes

A           float64
B    datetime64[us]
C           float32
D             int32
E          category
F               str
dtype: object

In [51]:
# 컬럼 이름 목록
df2.columns

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='str')

In [52]:
# 컬럼 선택(Series 반환)
#df2.A
df2['A']  # 안전한 방식

0    1.0
1    1.0
2    1.0
3    1.0
Name: A, dtype: float64

In [53]:
# 결측치(데이터가 비어 있는 값) 제외 개수
df2.count()

A    4
B    4
C    4
D    4
E    4
F    4
dtype: int64

In [54]:
# 컬럼명앞에 문자열 추가
df2.add_prefix("pre_")

   pre_A      pre_B  pre_C  pre_D  pre_E pre_F
0    1.0 2013-01-02    1.0      3   test   foo
1    1.0 2013-01-02    1.0      3  train   foo
2    1.0 2013-01-02    1.0      3   test   foo
3    1.0 2013-01-02    1.0      3  train   foo

In [55]:
# 중복행 확인
df2.duplicated()

0    False
1    False
2     True
3     True
dtype: bool

In [56]:
# Viewing data
df.head( )

                   A         B         C         D
2013-01-01  0.150654  1.901648 -0.890335  1.205825
2013-01-02  1.780011 -1.229151 -0.118814  2.458067
2013-01-03  0.086420 -0.740265 -1.428083  0.093868
2013-01-04  0.971432  0.721757 -1.443037  0.103568
2013-01-05  0.102880  0.802461  0.213550 -1.079248

In [57]:
df.head(3)

                   A         B         C         D
2013-01-01  0.150654  1.901648 -0.890335  1.205825
2013-01-02  1.780011 -1.229151 -0.118814  2.458067
2013-01-03  0.086420 -0.740265 -1.428083  0.093868

In [58]:
df.tail()

                   A         B         C         D
2013-01-02  1.780011 -1.229151 -0.118814  2.458067
2013-01-03  0.086420 -0.740265 -1.428083  0.093868
2013-01-04  0.971432  0.721757 -1.443037  0.103568
2013-01-05  0.102880  0.802461  0.213550 -1.079248
2013-01-06  0.411632  0.176465 -0.116215 -1.248752

In [59]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')

In [60]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='str')

In [61]:
df.to_numpy()

array([[ 0.15065441,  1.90164818, -0.89033478,  1.20582492],
       [ 1.78001073, -1.22915137, -0.11881419,  2.45806696],
       [ 0.08642041, -0.74026548, -1.42808253,  0.09386787],
       [ 0.97143183,  0.72175684, -1.44303731,  0.10356768],
       [ 0.10287964,  0.80246139,  0.21355048, -1.07924824],
       [ 0.41163246,  0.17646498, -0.11621488, -1.24875166]])

In [62]:
df2.dtypes

A           float64
B    datetime64[us]
C           float32
D             int32
E          category
F               str
dtype: object

In [63]:
# 통계 요약
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.583838  0.272152 -0.630489  0.255555
std    0.674849  1.133727  0.721471  1.403421
min    0.086420 -1.229151 -1.443037 -1.248752
25%    0.114823 -0.511083 -1.293646 -0.785969
50%    0.281143  0.449111 -0.504574  0.098718
75%    0.831482  0.782285 -0.116865  0.930261
max    1.780011  1.901648  0.213550  2.458067

In [64]:
# 데이터 전치
df.T

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    0.150654    1.780011    0.086420    0.971432    0.102880    0.411632
B    1.901648   -1.229151   -0.740265    0.721757    0.802461    0.176465
C   -0.890335   -0.118814   -1.428083   -1.443037    0.213550   -0.116215
D    1.205825    2.458067    0.093868    0.103568   -1.079248   -1.248752

In [65]:
# axis=0 -> 행인덱스 정렬
# axis=1 -> 컬럼이름으로 정렬
df.sort_index(axis=1, ascending=False)

                   D         C         B         A
2013-01-01  1.205825 -0.890335  1.901648  0.150654
2013-01-02  2.458067 -0.118814 -1.229151  1.780011
2013-01-03  0.093868 -1.428083 -0.740265  0.086420
2013-01-04  0.103568 -1.443037  0.721757  0.971432
2013-01-05 -1.079248  0.213550  0.802461  0.102880
2013-01-06 -1.248752 -0.116215  0.176465  0.411632

In [66]:
df.sort_index(ascending=False)

                   A         B         C         D
2013-01-06  0.411632  0.176465 -0.116215 -1.248752
2013-01-05  0.102880  0.802461  0.213550 -1.079248
2013-01-04  0.971432  0.721757 -1.443037  0.103568
2013-01-03  0.086420 -0.740265 -1.428083  0.093868
2013-01-02  1.780011 -1.229151 -0.118814  2.458067
2013-01-01  0.150654  1.901648 -0.890335  1.205825

In [67]:
df.sort_values(by="B", ascending=False)

                   A         B         C         D
2013-01-01  0.150654  1.901648 -0.890335  1.205825
2013-01-05  0.102880  0.802461  0.213550 -1.079248
2013-01-04  0.971432  0.721757 -1.443037  0.103568
2013-01-06  0.411632  0.176465 -0.116215 -1.248752
2013-01-03  0.086420 -0.740265 -1.428083  0.093868
2013-01-02  1.780011 -1.229151 -0.118814  2.458067

## Selection by label

In [68]:
# getitem
df2['A']

0    1.0
1    1.0
2    1.0
3    1.0
Name: A, dtype: float64

In [69]:
df.A

2013-01-01    0.150654
2013-01-02    1.780011
2013-01-03    0.086420
2013-01-04    0.971432
2013-01-05    0.102880
2013-01-06    0.411632
Freq: D, Name: A, dtype: float64

In [ ]:
# 컬럼 레이블로 여러 컬럼을 선택 -> subset, rearange
df[['B','A']]

                   B         A
2013-01-01  1.901648  0.150654
2013-01-02 -1.229151  1.780011
2013-01-03 -0.740265  0.086420
2013-01-04  0.721757  0.971432
2013-01-05  0.802461  0.102880
2013-01-06  0.176465  0.411632

In [ ]:
# slice 행 레이블
df['20130101':'20130102']

                   A         B         C         D
2013-01-01  0.150654  1.901648 -0.890335  1.205825
2013-01-02  1.780011 -1.229151 -0.118814  2.458067

In [ ]:
# slice : 행인덱스
df[0:2]

                   A         B         C         D
2013-01-01  0.150654  1.901648 -0.890335  1.205825
2013-01-02  1.780011 -1.229151 -0.118814  2.458067

In [74]:
df.loc['20130101':'20130102', ['A','B']]

                   A         B
2013-01-01  0.150654  1.901648
2013-01-02  1.780011 -1.229151

In [ ]:
df

                   A         B         C         D
2013-01-01  0.150654  1.901648 -0.890335  1.205825
2013-01-02  1.780011 -1.229151 -0.118814  2.458067
2013-01-03  0.086420 -0.740265 -1.428083  0.093868
2013-01-04  0.971432  0.721757 -1.443037  0.103568
2013-01-05  0.102880  0.802461  0.213550 -1.079248
2013-01-06  0.411632  0.176465 -0.116215 -1.248752

In [ ]:
# date[0] <- 행 레이블 리스트(또는 인덱스)에서 첫 번째 값
df.loc[dates[0]]

A    0.150654
B    1.901648
C   -0.890335
D    1.205825
Name: 2013-01-01 00:00:00, dtype: float64

In [86]:
df.loc[dates[0],"A"]

np.float64(0.15065441398452792)

In [88]:
df.at[dates[0], "A"]

np.float64(0.15065441398452792)

## selection by position

In [89]:
df.iloc[3]

A    0.971432
B    0.721757
C   -1.443037
D    0.103568
Name: 2013-01-04 00:00:00, dtype: float64

In [90]:
df.iloc[3:5, 0:2]

                   A         B
2013-01-04  0.971432  0.721757
2013-01-05  0.102880  0.802461

In [95]:
df.iloc[[1,2,4],[0,2]]

                   A         C
2013-01-02  1.780011 -0.118814
2013-01-03  0.086420 -1.428083
2013-01-05  0.102880  0.213550

In [96]:
# 
df.iloc[1,1]

np.float64(-1.2291513683683744)

## boolean indexing

In [100]:
df[df["A"]>0.4]

                   A         B         C         D
2013-01-02  1.780011 -1.229151 -0.118814  2.458067
2013-01-04  0.971432  0.721757 -1.443037  0.103568
2013-01-06  0.411632  0.176465 -0.116215 -1.248752

In [101]:
df[df >0]

                   A         B        C         D
2013-01-01  0.150654  1.901648      NaN  1.205825
2013-01-02  1.780011       NaN      NaN  2.458067
2013-01-03  0.086420       NaN      NaN  0.093868
2013-01-04  0.971432  0.721757      NaN  0.103568
2013-01-05  0.102880  0.802461  0.21355       NaN
2013-01-06  0.411632  0.176465      NaN       NaN

In [102]:
# 필터링
df3 = df.copy()
df3["E"] = ['one','one','two','three','four','three']
df3

                   A         B         C         D      E
2013-01-01  0.150654  1.901648 -0.890335  1.205825    one
2013-01-02  1.780011 -1.229151 -0.118814  2.458067    one
2013-01-03  0.086420 -0.740265 -1.428083  0.093868    two
2013-01-04  0.971432  0.721757 -1.443037  0.103568  three
2013-01-05  0.102880  0.802461  0.213550 -1.079248   four
2013-01-06  0.411632  0.176465 -0.116215 -1.248752  three

In [103]:
df3[df3["E"].isin(['two','four'])]

                  A         B         C         D     E
2013-01-03  0.08642 -0.740265 -1.428083  0.093868   two
2013-01-05  0.10288  0.802461  0.213550 -1.079248  four

## Setting

In [110]:
s1 = pd.Series([1,2,3,4,5,6], index=pd.date_range("20130201", periods=6))

df['F'] = s1
df

                   A         B         C         D   F
2013-01-01  0.150654  1.901648 -0.890335  1.205825 NaN
2013-01-02  1.780011 -1.229151 -0.118814  2.458067 NaN
2013-01-03  0.086420 -0.740265 -1.428083  0.093868 NaN
2013-01-04  0.971432  0.721757 -1.443037  0.103568 NaN
2013-01-05  0.102880  0.802461  0.213550 -1.079248 NaN
2013-01-06  0.411632  0.176465 -0.116215 -1.248752 NaN

In [111]:
df.at[dates[0],'A']

np.float64(0.15065441398452792)

In [114]:
df.iat[0,1] = 0
df.iat[0,1]

np.float64(0.0)

In [116]:
df.mean(axis=1)

2013-01-01    0.116536
2013-01-02    0.722528
2013-01-03   -0.497015
2013-01-04    0.088430
2013-01-05    0.009911
2013-01-06   -0.194217
Freq: D, dtype: float64

In [118]:
s = pd.Series([1, 3, 5, np.nan, 6, 8], index=dates).shift(2)
s

2013-01-01    NaN
2013-01-02    NaN
2013-01-03    1.0
2013-01-04    3.0
2013-01-05    5.0
2013-01-06    NaN
Freq: D, dtype: float64

In [130]:
s = pd.Series(np.random.randint(0, 7, size=10))
s.value_counts()

1    3
5    2
0    2
6    2
3    1
Name: count, dtype: int64

In [131]:
s = pd.Series(["A", "B", "C", "Aaba", "Baca", np.nan, "CABA", "dog", "cat"])
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: str

In [ ]:
# randn = 표준 정규분포(standard normal distribution)에서 난수 생성
# 정규분포 : 평균을 중심으로 좌우 대칭인 종 모양의 분포. 가운데 평균값이 가장 많이 몰림. 완전히 대칭
# 평균(mean) = 0   표준편차(std) = 1

df4 = pd.DataFrame(np.random.randn(10, 4))
df4

          0         1         2         3
0 -0.103166 -0.170858 -0.874715  0.209117
1  0.854642  0.333953  1.397684 -2.374869
2 -0.211422  0.729049 -0.634001  0.480412
3  0.114000  0.548258  0.527614  1.825472
4  0.750899  1.281172  0.673740 -0.573349
5 -0.304495 -0.624904  1.343964  1.258318
6  0.851099  1.469408  1.502841  0.401033
7 -1.278401 -0.293612 -0.715340  2.042759
8  0.430474  0.563231 -0.270902 -0.346746
9  0.266939 -1.598490  0.414787  0.340680

In [134]:
pieces = [df4[:3], df4[3:7], df4[7:]]
pd.concat(pieces)

          0         1         2         3
0 -0.103166 -0.170858 -0.874715  0.209117
1  0.854642  0.333953  1.397684 -2.374869
2 -0.211422  0.729049 -0.634001  0.480412
3  0.114000  0.548258  0.527614  1.825472
4  0.750899  1.281172  0.673740 -0.573349
5 -0.304495 -0.624904  1.343964  1.258318
6  0.851099  1.469408  1.502841  0.401033
7 -1.278401 -0.293612 -0.715340  2.042759
8  0.430474  0.563231 -0.270902 -0.346746
9  0.266939 -1.598490  0.414787  0.340680