In [1]:
# https://wikidocs.net/296075  참고사이트
import numpy as np
import pandas as pd

In [13]:
df  = pd.read_csv('student.csv')
df

    이름  나이 성별  점수
0  김철수  25  남  88
1  박영희  23  여  92
2  이민수  28  남  75
3  최지민  26  여  95

In [14]:
high_score = df[df['점수']>=90]
high_score

    이름  나이 성별  점수
1  박영희  23  여  92
3  최지민  26  여  95

In [15]:
condition = ( df['성별']=='여') & (df['나이']<25)
filtered_dt = df[condition]
print("\n여성이면서 25세 미만인 학생:")
print(filtered_dt)

여성이면서 25세 미만인 학생:
    이름  나이 성별  점수
1  박영희  23  여  92

In [16]:
gender_man=df[df['성별']=='남']
gender_man

    이름  나이 성별  점수
0  김철수  25  남  88
2  이민수  28  남  75

In [17]:
df.drop('성별', axis=1)

    이름  나이  점수
0  김철수  25  88
1  박영희  23  92
2  이민수  28  75
3  최지민  26  95

In [22]:
df['합계']=df['점수'].apply(lambda x: x+5)
df.drop('총점', axis=1)

    이름  나이 성별  점수   합계
0  김철수  25  남  88   93
1  박영희  23  여  92   97
2  이민수  28  남  75   80
3  최지민  26  여  95  100

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      4 non-null      str
 1   나이      4 non-null      int64
 2   성별      4 non-null      str
 3   점수      4 non-null      int64
dtypes: int64(2), str(2)
memory usage: 260.0 bytes

In [6]:
df.describe()

              나이         점수
count   4.000000   4.000000
mean   25.500000  87.500000
std     2.081666   8.812869
min    23.000000  75.000000
25%    24.500000  84.750000
50%    25.500000  90.000000
75%    26.500000  92.750000
max    28.000000  95.000000

In [7]:
df.rename(columns={'이름': '학생명', '성별': '성별구분'}, inplace=True)
df

   학생명  나이 성별구분  점수
0  김철수  25    남  88
1  박영희  23    여  92
2  이민수  28    남  75
3  최지민  26    여  95

In [8]:
df[df['점수']>=90]

   학생명  나이 성별구분  점수
1  박영희  23    여  92
3  최지민  26    여  95

In [9]:
df = pd.read_csv('products.csv')
df.describe().astype(int)

            가격  재고수량
count        3     3
mean   1100000    35
std     360555    13
min     800000    25
25%     900000    27
50%    1000000    30
75%    1250000    40
max    1500000    50